#!/bin/sh
#
# auth_server - this script starts and stops the auth_server daemon
#
# chkconfig: - 90 16
# description: auth_server controls all data
# processname: auth_server
# pidfile:     /var/run/auth_server.pid

# Source function library
. /etc/rc.d/init.d/functions

# Source networking configuration
. /etc/sysconfig/network

# Check that networking is up
[ "$NETWORKING" = "no" ] && exit 0

auth_server="/go/bin/auth_hall_server"
prog=$(basename $auth_server)
conf=/etc/gameServer/auth.conf
logfile=/var/log/gameServer/auth_runtime_log

lockfile=/var/lock/subsys/auth_server

start() {
	[ -x $auth_server ] || exit 5
	echo -n $"Starting $prog: "
	touch $logfile
	daemon $auth_server --conf=$conf >& $logfile &
	retval=$?
	echo
	[ $retval -eq 0 ] && touch $lockfile
	return $retval
}

stop() {
	echo -n $"Stopping $prog: "
	killall $prog
	retval=$?
	echo
	[ $retval -eq 0 ] && rm -f $lockfile
	return $retval
}

rh_status() {
	status $prog
}

rh_status_q() {
	rh_status >/dev/null 2>&1
}

case "$1" in
	start)
		rh_status_q && exit 0
		$1
		;;
	stop)
		rh_status_q || exit 0
		$1
		;;
	status)
		rh_status
		;;
	*)
		echo $"Usage: $0 {start|stop|status}"
		exit 2
esac
